package com.trainbooking.qr_train_ticket.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Element;
import com.trainbooking.qr_train_ticket.model.Ticket;
import com.trainbooking.qr_train_ticket.model.Train;
import com.trainbooking.qr_train_ticket.repository.TicketRepository;
import com.trainbooking.qr_train_ticket.repository.TrainRepository;
import org.springframework.stereotype.Service;
import java.time.format.DateTimeFormatter;

import java.io.ByteArrayOutputStream;

@Service
public class TicketPDFService {

    private final TicketRepository ticketRepo;
    private final TrainRepository trainRepo;
    private final TicketService ticketService;

    public TicketPDFService(
            TicketRepository ticketRepo,
            TrainRepository trainRepo,
            TicketService ticketService
    ) {
        this.ticketRepo = ticketRepo;
        this.trainRepo = trainRepo;
        this.ticketService = ticketService;
    }

    // ⭐ THIS METHOD IS WHAT CONTROLLER EXPECTS
    public byte[] generateTicketPDF(Long ticketId) {

        try {

            Ticket ticket = ticketRepo.findById(ticketId)
                    .orElseThrow(() -> new RuntimeException("Ticket not found"));

            Train train = trainRepo.findById(ticket.getTrainId())
                    .orElseThrow(() -> new RuntimeException("Train not found"));

            // Generate QR
            byte[] qrBytes = ticketService.generateQR(ticketId);

            Document document = new Document(PageSize.A5, 30, 30, 30, 30);
            ByteArrayOutputStream out = new ByteArrayOutputStream();

            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 9);

            Paragraph title = new Paragraph("TRAIN TICKET", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            Paragraph line = new Paragraph("--------------------------", normalFont);
            line.setAlignment(Element.ALIGN_CENTER);
            document.add(line);
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Ticket No : " + ticket.getTicketNumber(), headingFont));
            document.add(new Paragraph("Train No : " + train.getTrainNumber(), headingFont));
            DateTimeFormatter formatter =
                    DateTimeFormatter.ofPattern("dd-MMM-yyyy hh:mm a");

            String bookingDate =
                    ticket.getBookingDateTime().format(formatter);

            document.add(new Paragraph(
                    "Booking Date : " + bookingDate,
                    headingFont));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Passenger Name : " + ticket.getPassengerName(), headingFont));
            document.add(new Paragraph("Passenger Age : " + ticket.getPassengerAge(), headingFont));

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Train Name : " + train.getTrainName(),
                    headingFont));

            document.add(new Paragraph(
                    "Source : " + train.getSource(),
                    headingFont));

            document.add(new Paragraph(
                    "Destination : " + train.getDestination(),
                    headingFont));

            document.add(new Paragraph(
                    "Departure Time : " + train.getDepartureTime(),
                    headingFont));

            document.add(new Paragraph(
                    "Arrival Time : " + train.getArrivalTime(),
                    headingFont));

            document.add(new Paragraph("Seats Booked : " + ticket.getSeatsBooked(), headingFont));
            document.add(new Paragraph("Total Fare : ₹ " + (int) ticket.getTotalFare(), headingFont));

            document.add(new Paragraph(" "));
            Paragraph qrTitle = new Paragraph("QR CODE", headingFont);
            qrTitle.setAlignment(Element.ALIGN_CENTER);
            document.add(qrTitle);

            Image qrImage = Image.getInstance(qrBytes);
            qrImage.scaleAbsolute(130, 130);
            qrImage.setAlignment(Element.ALIGN_CENTER);

            document.add(qrImage);

            Paragraph footer = new Paragraph(
                    "Generated by QR Train Ticket Booking System",
                    footerFont);

            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(8);

            document.add(footer);

            document.close();

            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}